services:
  postgres_projeto23_db:
    image: postgres
    container_name: postgres_projeto23_db
    restart: always
    ports:
      - 4457:5432
    env_file:
      - ./back-end/.env
    volumes: 
      - pg_projeto23-db:/var/lib/postgresql/data

  node_projeto23_app:
    container_name: node_projeto23_app
    build: ./back-end
    ports:
      - 4458:5000
    depends_on:
      - postgres_projeto23_db
    env_file:
      - ./back-end/.env

  app_react:
    build: ./front-end
    container_name: app_react
    volumes:
      - build_react:/var/www/html

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - app_react
      - node_projeto23_app
      - postgres_projeto23_db

volumes:
  pg_projeto23-db:
  build_react:
