services:
  app_react_i:
    build: .
    container_name: app_react_i
    volumes:
      - build_react:/var/www/html

  nginx_i:
    build: ./nginx
    container_name: nginx_i
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - app_react_i

volumes:
  build_react:
