services:
  postgres_projeto23_db:
    image: postgres
    container_name: postgres_projeto23_db
    restart: always
    ports:
      - 4457:5432
    env_file:
      - .env
    volumes: 
      - pg_projeto23-db:/var/lib/postgresql/data

  node_projeto23_app:
    container_name: node_projeto23_app
    build: .
    ports:
      - 5000:5000
    depends_on:
      - postgres_projeto23_db
    env_file:
      - .env

volumes:
  pg_projeto23-db: