name: Pull Request
on: [pull_request]
jobs:
  PullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Run tests
        run: docker-compose -f ./back-end/docker-compose-tests.yml run node_app_github_actions npm run test